# Note: To make the app work, you need to have the following in the .htaccess file in 
# ~/public_html/longthinksapi.
# The part between the DO NOT REMOVE comments was generated by A2 cPanel / Passenger.
# The last two lines were added per
# https://stackoverflow.com/questions/63106913/python-flask-app-routing-in-cpanel-can-only-access-root-url?noredirect=1&lq=1

# # DO NOT REMOVE. CLOUDLINUX PASSENGER CONFIGURATION BEGIN
# PassengerAppRoot "/home/danbockn/projects/longthinksapi"
# PassengerBaseURI "/longthinksapi"
# PassengerPython "/home/danbockn/virtualenv/projects/longthinksapi/3.11/bin/python"
# PassengerAppLogFile "/home/danbockn/projects/longthinksapi/passenger.log"
# # DO NOT REMOVE. CLOUDLINUX PASSENGER CONFIGURATION END
#
# RewriteEngine On
# RewriteRule ^http://%{HTTP_HOST}%{REQUEST_URI} [END,NE]

from app import app as application

@application.after_request
def after_request(response):
    response.headers.add('Access-Control-Allow-Origin', '*')
    response.headers.add('Access-Control-Allow-Headers', 'Content-Type')
    return response